Use default factories for nested dataclass fields (#31)
Python 3.11 started using [stricter mutability checks for
dataclasses](https://github.com/python/cpython/commit/e029c53e1a408b89a4e3edf30a9b38b094f9c880)
which prevents the use of mutable dataclasses as default values:
```
  File "/home/lukasgeiger/reactions/projects/retrochimera/retrochimera/cli/train.py", line 99, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/lukasgeiger/miniconda3/lib/python3.14/dataclasses.py", line 1450, in dataclass
    return wrap(cls)
  File "/home/lukasgeiger/miniconda3/lib/python3.14/dataclasses.py", line 1440, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "/home/lukasgeiger/miniconda3/lib/python3.14/dataclasses.py", line 1066, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukasgeiger/miniconda3/lib/python3.14/dataclasses.py", line 917, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
                     f'{f.name} is not allowed: use default_factory')
ValueError: mutable default <class 'retrochimera.encoders.configs.ChemEncoderConfig'> for field encoder is not allowed: use default_factory
```

This PR switches to default factories to make this work with more recent
Python versions. Unfortunately this is less readable. An alternative
would be to make the dataclasses frozen so they can be hashed and used
as a default values.